### PR TITLE
Update CSI - Process - Exit an Intern --farsi-ir.md

### PR DESCRIPTION
**Pull request by raminmjj**
based on backlog: 26570

### CODE REVIEW

**Comment by raminmjj** [comment]
@zahra-ahangari please review these changes

@ZahraaaRezaeiii please review these changes

**Comment by ZahraaaRezaeiii** [comment]
Please indicate where the list is and how to access it

**Comment by ZahraaaRezaeiii** [comment]
That's ok. I don't think there is a need for a Telegram link.

**Comment by raminmjj** [comment]
@zahra-ahangari please review and merge these changes

**Review by zahra-ahangari — APPROVED** [review]

**Pull request merged**
