### PR TITLE
Update CSI - Process - Coordinate Interns Weekly Meetings --farsi-ir.md

### PR DESCRIPTION
**Pull request by shab-sa**
Add penalty mechanism for not attending technical sessions without prior notice.

### CODE REVIEW

**Review by ZahraaaRezaeiii — COMMENTED** [review]
Thanks, that's good

**Comment by shab-sa** [comment]
@zahra-ahangari  can you please review the changes I made to this document and if this is ok, merge this pull request.

**Comment by zahra-ahangari** [comment]
Please check some comments I've left on your intended changes. @shab-sa

**Review by zahra-ahangari — CHANGES_REQUESTED** [review]

**Comment by shab-sa** [comment]
Thank You Zahra. I edited the file based on your comments. Can you please Check it again @zahra-ahangari .

**Review by ZahraaaRezaeiii — COMMENTED** [review]
that's ok

**Review by zahra-ahangari — APPROVED** [review]

**Pull request merged**
